# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'licenta_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from View.View_config import *
import os
from View.manage_teams import Ui_Form
from View.waiting_widget import Waiting_Widget
import asyncio
from asyncqt import QEventLoop
from Controller.Controller import Controller


class Ui_MainWindow(object):
    def setupUi(self, MainWindow,controller):

        self.controller=controller
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(623, 394)

        self.teams_ui=None
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(250, 300, 93, 28))
        self.btn_start.setObjectName("btn_start")
        self.btn_start.clicked.connect(self.start)

        self.btn_teams = QtWidgets.QPushButton(self.centralwidget)
        self.btn_teams.setGeometry(QtCore.QRect(465, 300, 101, 28))
        self.btn_teams.setObjectName("btn_teams")
        self.btn_teams.clicked.connect(self.show_manage_teams)

        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(20, 30, 133, 22))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(20, 80, 133, 22))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(20, 10, 61, 16))
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(20, 60, 55, 16))
        self.label_password.setObjectName("label_password")
        self.label_teams = QtWidgets.QLabel(self.centralwidget)
        self.label_teams.setGeometry(QtCore.QRect(180, 10, 55, 16))
        self.label_teams.setObjectName("label_teams")
        self.label_agent = QtWidgets.QLabel(self.centralwidget)
        self.label_agent.setGeometry(QtCore.QRect(460, 60, 55, 16))
        self.label_agent.setObjectName("label_agent")
        self.label_runs = QtWidgets.QLabel(self.centralwidget)
        self.label_runs.setGeometry(QtCore.QRect(460, 10, 121, 16))
        self.label_runs.setObjectName("label_runs")
        self.lineEdit_runs = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_runs.setGeometry(QtCore.QRect(460, 30, 113, 22))
        self.lineEdit_runs.setObjectName("lineEdit_runs")
        self.label_mode = QtWidgets.QLabel(self.centralwidget)
        self.label_mode.setGeometry(QtCore.QRect(20, 120, 55, 16))
        self.label_mode.setObjectName("label_mode")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(30, 300, 93, 28))
        self.btn_exit.setObjectName("btn_exit")
        self.btn_exit.clicked.connect(self.exit)
        self.listWidget_teams = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_teams.setGeometry(QtCore.QRect(180, 30, 231, 211))
        self.listWidget_teams.setObjectName("listWidget")
        self.listWidget_mode = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_mode.setGeometry(QtCore.QRect(20, 140, 133, 101))
        self.listWidget_mode.setObjectName("listWidget_mode")
        self.listWidget_bot = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_bot.setGeometry(QtCore.QRect(460, 80, 111, 161))
        self.listWidget_bot.setObjectName("listWidget_bot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 623, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.populate_lists()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_teams.setText(_translate("MainWindow", "Manage Teams"))
        self.label_username.setText(_translate("MainWindow", "Username"))
        self.label_password.setText(_translate("MainWindow", "Password"))
        self.label_teams.setText(_translate("MainWindow", "Teams"))
        self.label_agent.setText(_translate("MainWindow", "Bots"))
        self.label_runs.setText(_translate("MainWindow", "Games to be played"))
        self.label_mode.setText(_translate("MainWindow", "Bot Mode"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))

    def populate_lists(self):

        self.listWidget_teams.clear()
        self.listWidget_mode.clear()
        self.listWidget_bot.clear()
        self.lineEdit_username.setText("")
        self.lineEdit_password.setText("")

        teams=self.controller.read_teams()
        self.listWidget_teams.addItem(teams)

        self.listWidget_bot.addItem("Q-learning")
        self.listWidget_bot.addItem("MCTS")
        self.listWidget_bot.addItem("Minmax")

        self.listWidget_mode.addItem("Search Ladder")
        self.listWidget_mode.addItem("Accept Challenge")

        self.lineEdit_runs.setText("1")

    def exit(self):
        sys.exit(app.exec_())

    def show_manage_teams(self):
        self.teams_ui=Ui_Form(self,controller)
        self.teams_ui.show()
        MainWindow.hide()

    def back(self):
        MainWindow.show()
        self.populate_lists()

    def start(self):
        # team=self.listWidget_teams.currentItem().text()
        #
        # bot=self.listWidget_bot.currentItem().text()
        # if bot=='Minmax':
        #     bot='MinMax_Classic'
        # elif bot=='Q-learning':
        #     bot='RL_agent'
        #
        # mode=self.listWidget_mode.currentItem().text()
        # mode=mode.upper()
        # mode=mode.replace(' ','_')
        #
        games=self.lineEdit_runs.text()
        #
        # username=self.lineEdit_username.text()
        #
        # password=self.lineEdit_password.text()
        #
        #
        # text="WEBSOCKET_URI=sim.smogon.com:8000\n"\
        #         "PS_USERNAME={}\n" \
        #         "PS_PASSWORD={}\n"\
        #         "BOT_MODE={}\n"\
        #         "POKEMON_MODE=gen7ou\n"\
        #         "RUN_COUNT={}\n"\
        #         "USER_TO_CHALLENGE=rl_test2\n"\
        #         "BATTLE_BOT={}\n"\
        #         "TEAM_NAME=gen7/{}\n".format(username,password,mode,games,bot,team)
        # self.controller.write_env(text)
        self.waiting_ui=Waiting_Widget(self,games)
        self.waiting_ui.show()
        MainWindow.hide()
        self.waiting_ui.start_bot()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loop = QEventLoop(app)
    asyncio.set_event_loop(loop)
    controller=Controller()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow,controller)
    MainWindow.show()
    sys.exit(app.exec_())
