# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'licenta_manage_teams.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget
from PyQt5.QtCore import QThreadPool
from PyQt5.QtGui import QMovie
from View.Worker import Worker
import asyncio
from run import showdown


class WaitingWidget(QWidget):
    def __init__(self,parent,games=None):
        super().__init__()
        self.threadpool = QThreadPool()
        self.parent=parent
        self.resize(300,200)
        self.games_to_play=games
        self.games_played=0
        self.label_played = QtWidgets.QLabel(self)
        self.label_played.setGeometry(QtCore.QRect(100, 80, 111, 16))
        self.label_played.setObjectName("label_played")

        # self.label_gif = QtWidgets.QLabel(self)
        # self.label_gif.setGeometry(QtCore.QRect(105, 130, 100, 100))
        # self.label_gif.setObjectName("label_gif")

        self.listWidget_played = QtWidgets.QListWidget(self)
        self.listWidget_played.setGeometry(QtCore.QRect(100, 100, 111, 21))
        self.listWidget_played.setObjectName("listWidget_played")
        self.label_to_play = QtWidgets.QLabel(self)
        self.label_to_play.setGeometry(QtCore.QRect(100, 30, 111, 16))
        self.label_to_play.setObjectName("label_to_play")
        self.listWidget_to_play = QtWidgets.QListWidget(self)
        self.listWidget_to_play.setGeometry(QtCore.QRect(100, 50, 111, 21))
        self.listWidget_to_play.setObjectName("listWidget_to_play")
        self.btn_stop = QtWidgets.QPushButton(self)
        self.btn_stop.setGeometry(QtCore.QRect(105, 130, 93, 28))
        self.btn_stop.setObjectName("btn_stop")
        self.btn_stop.clicked.connect(self.stop)
        self.btn_stop.hide()

        # self.gif = QMovie('View/loading.gif')
        # self.label_gif.setMovie(self.gif)
        # self.gif.start()
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Waiting Window"))
        self.btn_stop.setText(_translate("Form", "Back"))
        self.label_played.setText(_translate("Form", "Games played"))
        self.label_to_play.setText(_translate("Form", "Games to play"))


    def populate_lists(self,games):
        self.listWidget_played.clear()
        self.listWidget_to_play.clear()

        self.games_played=games
        if self.games_played==int(self.games_to_play):
            self.show_back_button()
        self.listWidget_to_play.addItem(self.games_to_play)
        self.listWidget_played.addItem(str(self.games_played))

    def show_back_button(self):
        self.btn_stop.show()

    def start_bot(self):
        loop = asyncio.get_event_loop()
        self.worker = Worker(showdown,self.populate_lists,loop)
        self.threadpool.start(self.worker)

    def setGames(self,games):
        self.games_to_play=games



    def stop(self):
        self.threadpool.clear()
        self.parent.back()
        self.close()
